project/faq/urls.py
from django.conf.urls import patterns, url
from .views import SubmitFAQ, SubmitFAQThanks,QuestionDetail, QuestionList

urlpatterns = patterns('',
    url(r'^$', QuestionList.as_view(), name='faq_question_list'),
    url(r'^(?P<slug>[\w-]+)$', QuestionDetail.as_view(), name='faq_question_detail'),

    # TODO: anonymous users can submit questions, that need approval from the editors
    # url(r'^submit$', SubmitFAQ.as_view(), 'faq_submit'),
    # url(r'^submit/thanks$', SubmitFAQThanks.as_view(), 'faq_submit_thanks'),
)

project/openaid/codelists/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from . import views

# load admin modules
from django.contrib import admin
admin.autodiscover()


urls = (
    url(r'^sectors/(?P<code>\w+)/$', views.SectorView.as_view(), name='sector-detail'),
    url(r'^recipients/(?P<code>\w+)/$', views.RecipientView.as_view(), name='recipient-detail'),
    url(r'^channels/(?P<code>\w+)/$', views.ChannelView.as_view(), name='channel-detail'),
    url(r'^agencies/(?P<code>\w+)/$', views.AgencyView.as_view(), name='agency-detail'),
    url(r'^aid_types/(?P<code>\w+)/$', views.AidTypeView.as_view(), name='aid_type-detail'),
)
urlpatterns = patterns('', *urls)

project/openaid/pages/urls.py
# -*- coding: utf-8 -*-
from .views import CooperazioneView, StaticPageView
from django.conf.urls import patterns, url, include
from .pages import  footer_sections, cooperazione_pages


urls = []

for section_id, footer_section_pages in footer_sections.items():
    for page_url_name, page_label in footer_section_pages.items():
        urls.append(
            url(r"^{0}$".format(page_url_name.replace('_', '-')),
                StaticPageView.as_view(
                    template_name="footer_{0}_{1}.html".format(section_id, page_url_name),
                    page_url_name=page_url_name,
                    page_label=page_label
                ),
                name=page_url_name
            )
        )


for page_url_name, page_label in cooperazione_pages.items():
    urls.append(
        url(r"^{0}$".format(page_url_name.replace('_', '-')),
            CooperazioneView.as_view(
                template_name="coop_{0}.html".format(page_url_name),
                page_url_name=page_url_name,
                page_label=page_label
            ),
            name=page_url_name
        )
    )

urlpatterns = patterns('', *urls)

project/openaid/projects/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from haystack.views import search_view_factory
from . import views


urls = (
    url(r'^initiative/(?P<code>\d+)/$', views.InitiativeDetail.as_view(), name='initiative-detail'),
    url(r'^project/list/$', views.ProjectList.as_view(), name='project-list'),
    url(r'^project/(?P<pk>\d+)/$', views.ProjectDetail.as_view(), name='project-detail'),
    # NOTE: search/ is here for back-compatibility
    url(r'^search/', search_view_factory(views.SearchFacetedProjectView), name='search'),
    url(r'project/search/', search_view_factory(views.SearchFacetedProjectView), name='project-search'),
    url(r'initiative/search/', search_view_factory(views.SearchFacetedInitiativeView), name='initiative-search'),

)
urlpatterns = patterns('', *urls)

project/openaid/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.routers import DefaultRouter
from . import views
from rest_framework.views import APIView
from .projects.views import ProjectViewSet, ActivityViewSet, ChannelReportedViewSet
from .codelists.views import SectorViewSet, RecipientViewSet, ChannelViewSet, AidTypeViewSet, AgencyViewSet, \
    FinanceTypeViewSet, DonorViewSet
from sitemap import sitemaps

# load admin modules
from django.contrib import admin
admin.autodiscover()


# Create a router and register our viewsets with it.
class APIRouter(DefaultRouter):

    def get_api_root_view(self):
        """
        Return a view to use as the API root.
        """
        api_root_dict = {}
        list_name = self.routes[0].name
        for prefix, viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)

        class APIRoot(APIView):
            """
            This is the root entry-point of the OpenAID APIs.

            The APIs are read-only, freely accessible to all through HTTP requests at ``http://openaid.esteri.it/api``.

            Responses are emitted in both **browseable-HTML** and **JSON** formats (``http://openaid.esteri.it/api/.json``)

            To serve all requests and avoid slow responses or downtimes due to misuse, we limit the requests rate.
            When accessing the API **anonymously**, your client is limited to **12 requests per minute** from the same IP.
            You can contact us to become an **authenticated API user** (it's still free),
            then the rate-limit would be lifted to **1 request per second**.

            If for some reasons, you need to scrape all the OpenAID data, please consider a bulk **CSV download**.

            See the ``http://openaid.esteri.it/scarica-dati/`` page in the web site.
            """
            _ignore_model_permissions = True

            def get(self, request, format=None):
                ret = {}
                for key, url_name in api_root_dict.items():
                    ret[key] = reverse(url_name, request=request, format=format)
                return Response(ret)

        return APIRoot.as_view()

router = APIRouter(trailing_slash=False)
router.register(r'projects', ProjectViewSet)
router.register(r'activities', ActivityViewSet)
router.register(r'sectors', SectorViewSet)
router.register(r'recipients', RecipientViewSet)
router.register(r'channels', ChannelViewSet)
router.register(r'aid_types', AidTypeViewSet)
router.register(r'agencies', AgencyViewSet)
router.register(r'finance_types', FinanceTypeViewSet)


urlpatterns = [
    url(r'^$', views.Home.as_view()),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^select2/', include('django_select2.urls')),
]

openaid_urls = (
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^widget/$', views.Widget.as_view(), name='widget'),
    url(r'^widget/embed/$', views.WidgetEmbed.as_view()),
    url(r'^news/', include('blog.urls')),
    url(r'^faq/', include('faq.urls')),
    url(r'^projects/', include('openaid.projects.urls', namespace='projects')),
    url(r'^code-lists/', include('openaid.codelists.urls', namespace='codelists')),
    url(r'^', include('openaid.pages.urls')),
)
urlpatterns += i18n_patterns('', *openaid_urls)

# static and media urls not works with DEBUG = True, see static function.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('', url(r'^__debug__/', include(debug_toolbar.urls)), )

# Work in progress url
if settings.MAINTENANCE:
    urlpatterns[0] = url(r'^.*$', TemplateView.as_view(template_name='work_in_progress.html'))


# Sitemap: disabled in staging
if settings.INSTANCE_TYPE != 'staging':

    urlpatterns += patterns('django.contrib.sitemaps.views',
        (r'^sitemap\.xml$', 'index', {'sitemaps': sitemaps}),
        (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap', {'sitemaps': sitemaps}),
        (r'^robots\.txt$', include('robots.urls')),
    )

project/openaid/codelists/views.py
from django.views.generic import DetailView
from django.conf import settings
from . import models
from .. import views
from .. import contexts
from openaid.codelists import serializers
from openaid.views import OpenaidViewSet
from openaid import utils

class CodeListView(views.MapFiltersContextMixin, DetailView):
    slug_field = 'code'
    slug_url_kwarg = 'code'

    def get_codelist_filter(self):
        if not hasattr(self, '_codelist_filter'):
            setattr(self, '_codelist_filter', {
                '%s__in' % self.model.code_list: self.object.get_descendants_pks(include_self=True)
            })
        return getattr(self, '_codelist_filter')

    def get_context_data(self, **kwargs):
        context = super(CodeListView, self).get_context_data(**kwargs)
        context = DetailView.get_context_data(self, **context)

        # adds model name to the context so the app knows which page of codelist it's rendering
        model_name = self.model.__name__.lower()
        context.update({'model_name': model_name})

        year_value = utils.sanitize_get_param(int,self.request.GET.get('year'),contexts.END_YEAR,top=contexts.END_YEAR,length=4)
        # depending on which codelist page it's rendereing adds top projs or top inits
        if model_name in ['agency', 'aidtype']:
            context['top_projects'] = self.object.top_projects(year=year_value)
        elif model_name in ['recipient', 'sector']:
            top_initiatives = self.object.top_initiatives()
            context['top_initiatives'] = top_initiatives[:settings.TOP_ELEMENTS_NUMBER]
            context['top_initiatives_count'] = len(top_initiatives)

        return context

    def get_map_filters(self):
        filters = super(CodeListView, self).get_map_filters()
        filters.update(self.get_codelist_filter())
        return filters


class SectorView(CodeListView):
    model = models.Sector


class RecipientView(CodeListView):
    model = models.Recipient


class ChannelView(CodeListView):
    model = models.Channel


class AidTypeView(CodeListView):
    model = models.AidType


class AgencyView(CodeListView):
    model = models.Agency


class CodelistOpenaidViewSet(OpenaidViewSet):
    lookup_field = 'code'


class SectorViewSet(CodelistOpenaidViewSet):
    queryset = models.Sector.objects.all()
    serializer_class = serializers.SectorSerializer


class RecipientViewSet(CodelistOpenaidViewSet):
    queryset = models.Recipient.objects.all()
    serializer_class = serializers.RecipientSerializer


class ChannelViewSet(CodelistOpenaidViewSet):
    queryset = models.Channel.objects.all()
    serializer_class = serializers.ChannelSerializer


class AidTypeViewSet(CodelistOpenaidViewSet):
    queryset = models.AidType.objects.all()
    serializer_class = serializers.AidTypeSerializer


class AgencyViewSet(CodelistOpenaidViewSet):
    queryset = models.Agency.objects.all()
    serializer_class = serializers.AgencySerializer


class FinanceTypeViewSet(CodelistOpenaidViewSet):
    queryset = models.FinanceType.objects.all()
    serializer_class = serializers.FinanceTypeSerializer


class DonorViewSet(CodelistOpenaidViewSet):
    queryset = models.Donor.objects.all()
    serializer_class = serializers.DonorSerializer

project/openaid/pages/views.py
# -*- coding: utf-8 -*-
import urls

from django.core.exceptions import ImproperlyConfigured
from django.views.generic import TemplateView
from django.conf import settings

class StaticPageView(TemplateView):
    """
    This view extends (monkey-patches, more precisely),
    the TemplateResponseMixin's get_template_names,
    in order to intercept the currently selected language code
    and modify the template_name.

    It is assumed that the templates will go under dedicated directory,
    named after the language codes, i.e.:

        - en
          - footer_chi_siamo.html
          - contatti.html
        - it
          - footer_chi_siamo.html
          - contatti.html

    """
    template_language = None
    page_url_name = None
    page_label = {}

    def get_template_names(self):
        """
        Returns a list of template names to be used for the request. Must return
        a list. May not be called if render_to_response is overridden.
        """
        if self.template_language is None:
            if self.request.LANGUAGE_CODE is None:
                raise ImproperlyConfigured(
                    "I18NTemplateView requires either a definition of "
                    "'template_language' or an implementation of 'get_template_language()'")
            else:
                self.template_language = self.request.LANGUAGE_CODE


        configured_languages = dict(settings.LANGUAGES).keys()
        if self.template_language is None:
            raise ImproperlyConfigured(
                "I18NTemplateView requires 'template_language' "
                "to be in one of the languages specified in the settings")

        if self.template_name is None:
            raise ImproperlyConfigured(
                "I18NTemplateView requires either a definition of "
                "'template_name' or an implementation of 'get_template_names()'")

        return ["{0}/{1}".format(self.template_language, self.template_name)]

    def get_context_data(self, **kwargs):
        context = super(StaticPageView, self).get_context_data(**kwargs)
        context['page_label'] = self.page_label
        context['page_url_name'] = self.page_url_name
        return context


class CooperazioneView(StaticPageView):
    """
    This view extends the I18NTemplateView, and is used to show
    the pages under cooperaizone_italiana.

    Basically, it injects a cooperazione_pages key, within the context.

    The cooperazione_pages is imported from the urls module (in this pages package)
    """

    def get_context_data(self, **kwargs):
        context = super(CooperazioneView, self).get_context_data(**kwargs)
        context['cooperazione_pages'] = urls.cooperazione_pages
        return context

project/openaid/views.py
from __future__ import print_function
from django.views.generic import TemplateView
from django.views.generic.base import ContextMixin
from rest_framework import viewsets
from blog.models import Entry
from django.conf import settings
from openaid import contexts
from openaid.codelists.models import Recipient
from openaid.projects.models import Project, Initiative
from openaid import utils


class MapFiltersContextMixin(ContextMixin):
    def get_context_data(self, **kwargs):
        return super(MapFiltersContextMixin, self).get_context_data(
            map_values=Recipient.get_map_totals(**self.get_map_filters()),
            **kwargs)

    def get_map_filters(self):
        # the exact lookup is necessary becouse year is already a lookup
        year_value = utils.sanitize_get_param(int,self.request.GET.get('year'),contexts.END_YEAR,top=contexts.END_YEAR,length=4)
        return {'year__exact': year_value}


class Home(MapFiltersContextMixin, TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        top_initiatives = Initiative.get_top_initiatives(is_home=True, )

        return super(Home, self).get_context_data(
            entries_list=Entry.objects.all().order_by('-published_at')[:1],
            top_initiatives=top_initiatives[:settings.TOP_ELEMENTS_NUMBER],
            top_initiatives_count=len(top_initiatives),
            **kwargs
        )

class Numbers(Home):
    template_name = 'pages/numbers.html'


class Widget(Home):
    template_name = 'widget.html'

    def get_context_data(self, **kwargs):
        return super(Widget, self).get_context_data(widget=True, **kwargs)


class WidgetEmbed(TemplateView):
    template_name = 'widget_embed.html'

    def get_context_data(self, **kwargs):
        from django.core.urlresolvers import reverse
        from django.contrib.staticfiles.templatetags.staticfiles import static
        url = self.request.build_absolute_uri(reverse('widget'))
        js_url = self.request.build_absolute_uri(static('js/widget.js'))

        return super(WidgetEmbed, self).get_context_data(widget_url=url,js_url=js_url, **kwargs)

class OpenaidViewSet(viewsets.ReadOnlyModelViewSet):
    """
    This viewset automatically provides `list` and `detail` actions.
    """
    paginate_by = 10
    paginate_by_param = 'page_size'
    max_paginate_by = 100


from rest_framework import generics


class OpenaidApiRoot(generics.GenericAPIView):
    """
    This is the root entry-point of the OpenCoesione APIs.

    The APIs are read-only, freely accessible to all through HTTP requests at ``http://www.opencoesione.gov/api``.

    Responses are emitted in both **browseable-HTML** and **JSON** formats (``http://www.opencoesione.gov/api/.json``)

    To serve all requests and avoid slow responses or downtimes due to misuse, we limit the requests rate.
    When accessing the API **anonymously**, your client is limited to **12 requests per minute** from the same IP.
    You can contact us to become an **authenticated API user** (it's still free),
    then the rate-limit would be lifted to **1 request per second**.

    Authentication is done through HTTP Basic Authentication.

    You can request a username/password to authenticate,
    by writing an email to the following address: opencoesione@dps.gov.it.

    If for some reasons, you need to scrape all the OpenCoesione data, please consider a bulk **CSV download**.
    See the ``http://www.opencoesione.gov.it/opendata/`` page in the web site.
    """

project/openaid/templates/commons/main_panel.html
{% load i18n icons humanize crs %}

<div class="row" id="codelist-chart-container">
    <div class="col-md-12">
        <div class="col-md-3">
            <h2>{% trans 'Aid during the time' %}</h2>
            {% if selected_facet %}
            <p>{% blocktrans %}The variation of resources committed and paid for Bilateral and Multi-bilateral development aid{% endblocktrans %}</p>
            {% else %}
            <p>{% blocktrans %}The variation of resources committed and paid for development aid.{% endblocktrans %}</p>
            {% endif %}
            <br><br>
            <p class="lead">
                <i class="fa fa-circle" style="font-size: 13px; color: #f7505a !important;"></i> {% trans "Committed" %} <br>
                <i class="fa fa-circle" style="font-size: 13px; color: #2b6a7c !important;"></i> {% trans "Used" %}
            </p>
        </div>
        <div class="col-md-9">
            <div id="time-chart"></div>
            <table class="hide" id="time-chart-table">
            <thead>
                <tr>
                    <th>Year</th>
                    <th>{% trans "Committed" %}</th>
                    <th>{% trans "Used" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for year, commitment, disbursement in years_values %}
                <tr>
                    <td>{{ year }}</td>
                    <td data-value="{{ commitment|stringformat:"f" }}">{{ commitment|currency }}</td>
                    <td data-value="{{ disbursement|stringformat:"f" }}">{{ disbursement|currency }}</td>
                </tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        {% include 'commons/years_bar.html' %}
    </div>
</div>

<div id="stats-panel">

    {% if not selected_facet %}{% include 'commons/aid_tabs.html' %}{% endif %}

    <div class="panel panel-default{% if not selected_facet %} stats-home{% endif %}">

        {% if selected_facet %}
            <div class="panel-heading">
                {% include 'commons/aid_tabs.html' %}
            </div>
            {% include 'commons/stats.html' %}
        {% else %}

        <!-- Tab panes -->
        <div class="tab-content panel-body">
            <div class="tab-pane active" id="bi-multi-tab">
                {% include 'commons/stats.html' %}
            </div>{% if not widget %}
            <div class="tab-pane" id="multi-tab">
                {% include 'commons/stats_multi.html' %}
            </div>
            <div class="tab-pane" id="total-aid-tab">
                {% include 'commons/stats_totals.html' %}
            </div>{% endif %}
        </div>
        {% endif %}
        {% if not widget %}
        <div class="panel-footer text-right">
            <small class="text-muted">{% trans 'Committed funds, amounts in euros.' %}</small>
        </div>
        {% endif %}
    </div>
</div>

project/openaid/templates/commons/share_buttons.html
<div class="addthis_toolbox addthis_default_style pull-right">
    <a class="addthis_button_preferred_1"></a>
    <a class="addthis_button_preferred_2"></a>
    <a class="addthis_button_preferred_3"></a>
    <a class="addthis_button_preferred_4"></a>
    <a class="addthis_button_compact"></a>
    <a class="addthis_counter addthis_bubble_style"></a>
</div>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid={{ addthis_profile }}"></script>

project/openaid/templates/commons/stats.html
{% load search_utils %}
{% load staticfiles %}
{% load i18n %}
{% load humanize %}
{% load icons %}
{% load crs %}

<div>

    {% if show_map %}
        <div class="map">
            <div id="map"></div>
        </div>
    {% endif %}

    {% if not widget %}
    <div class="row panel-pad stats-panel-columns">

        {% if sector_stats %}
            <div class="{% if columns == 3 %}col-md-4{% else %}col-md-6{% endif %}">
                <h3>{% trans 'What is it spent for?' %}</h3>
                <p class="twelve readmore">
{% blocktrans %}The purpose/sector of destination of a bilateral contribution should be selected
by answering the question “which specific area of the recipient’s economic or social structure is the transfer intended to foster”.
The sector classification does not refer to the type of goods or services provided by the donor.
Sector specific education or research activities (e.g. agricultural education) or construction of infrastructure (e.g. agricultural storage)
should be reported under the sector to which they are directed, not under education, construction, etc.{% endblocktrans %}
                    <a href="#" class="readmore-open">{% trans 'read more' %} {% icon 'caret-down' %}</a>
                    <a href="#" class="readmore-close">{% trans 'close' %} {% icon 'caret-up' %}</a>
                </p>

                <div id="donut-left"></div>

                <div class="no-table-responsive">
                    <table class="table table-condensed table-hover" data-chart="donut" data-container="donut-left">
                        <tbody>
                            {% for sector, tot in sector_stats %}
                                {% if tot > 0.0 %}
                                    <tr class="dotted">
                                        <td class="col-sm-8">
                                            {% if not selected_code_list %}
                                                <a href="{% url 'codelists:sector-detail' code=sector.code %}?year={{ selected_year }}" data-title="{{ sector.name }}">{{ sector.name }}</a>
                                            {% elif selected_code_list.code_list == 'sector' %}
                                                <span data-title="{{ sector.name }}"><a href="{% url 'codelists:sector-detail' code=sector.code %}">{{ sector.name }}</a></span>
                                            {% else %}
                                                <a href="{% search_url sector.code_list_facet sector.code %}&selected_facets={{ selected_facet }}:{{ selected_code_list.code }}&selected_facets=years:{{ selected_year }}" data-title="{{ sector.name }}">{{ sector.name }}</a>
                                            {% endif %}
                                        </td>
                                        <td class="col-sm-4"><span data-value="{{ tot|stringformat:"f" }}">{{ tot|currency }}</span></td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}

        {% if aid_stats %}
            <div class="{% if columns == 3 %}col-md-4{% else %}col-md-6{% endif %}">
                <h3>{% trans 'By means of?' %}</h3>
                <p class="twelve readmore">
{% blocktrans %}The typology identifies the modalities that are used in aid delivery. It classifies transfers from the donor to the first recipient of funds (e.g. the recipient country,
a multilateral organisation, or a basket fund).  It does not track the end uses of the funds, which is addressed in the sector classification and to some extent through the policy objective markers.{% endblocktrans %}
                    <a href="#" class="readmore-open">{% trans 'read more' %} {% icon 'caret-down' %}</a>
                    <a href="#" class="readmore-close">{% trans 'close' %} {% icon 'caret-up' %}</a>
                </p>
                <div id="donut1"></div>

                <div class="no-table-responsive">
                    <table class="table table-condensed table-hover" data-chart="donut" data-container="donut1">
                        <tbody>
                        {% for aid_type, tot in aid_stats %}
                            {% if tot > 0.0 %}
                                <tr class="dotted">
                                    <td class="col-sm-8">
                                        {% if not selected_code_list %}
                                            <a href="{% url 'codelists:aid_type-detail' code=aid_type.code %}?year={{ selected_year }}" data-title="{{ aid_type.name }}">{{ aid_type.name }}</a>
                                        {% elif selected_code_list.code_list == 'aid_type' %}
                                            <span data-title="{{ aid_type.name }}">{{ aid_type.name }}</span>
                                        {% else %}
                                            <a href="{% search_url aid_type.code_list_facet aid_type.code %}&selected_facets={{ selected_facet }}:{{ selected_code_list.code }}&selected_facets=years:{{ selected_year }}" data-title="{{ aid_type.name }}">{{ aid_type.name }}</a>
                                        {% endif %}

                                    </td>
                                    <td class="col-sm-4"><span data-value="{{ tot|stringformat:"f" }}">{{ tot|currency }}</span></td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>

                    </table>
                </div>
            </div>
        {% endif %}

        {% if agency_stats %}
            <div class="{% if columns == 3 %}col-md-4{% else %}col-md-6{% endif %}">
                <h3>{% trans 'Who funds?' %}</h3>
                <p class="twelve readmore">
{% blocktrans %}The extending agency is the government entity (central, state or local government agency
or department) financing the activity from its own budget. It is the budget holder, controlling the
activity on its own account. Agencies administering activities on behalf of other government
entities should not be reported as extending agencies but as channels of delivery.{% endblocktrans %}
                    <a href="#" class="readmore-open">{% trans 'read more' %} {% icon 'caret-down' %}</a>
                    <a href="#" class="readmore-close">{% trans 'close' %} {% icon 'caret-up' %}</a>
                </p>
                <div id="donut-right"></div>

                <div class="no-table-responsive">
                    <table class="table table-condensed table-hover" data-chart="donut" data-container="donut-right">
                        <tbody>
                        {% for agency, tot in agency_stats %}{% if tot > 0.0 %}
                        <tr class="dotted">
                            <td class="col-sm-8">
                                {% if not selected_code_list %}
                                    <a href="{% url 'codelists:agency-detail' code=agency.code %}?year={{ selected_year }}" data-title="{{ agency.name }}">{{ agency.name }}</a>
                                {% elif selected_code_list.code_list == 'agency' %}
                                    <span data-title="{{ agency.name }}">{{ agency.name }}</span>
                                {% else %}
                                    <a href="{% search_url agency.code_list_facet agency.code %}&selected_facets={{ selected_facet }}:{{ selected_code_list.code }}&selected_facets=years:{{ selected_year }}" data-title="{{ agency.name }}">{{ agency.name }}</a>
                                {% endif %}

                            </td>
                            <td class="col-sm-4"><span data-value="{{ tot|stringformat:"f" }}">{{ tot|currency }}</span></td>
                        </tr>
                        {% endif %}{% endfor %}
                        </tbody>

                    </table>
                </div>
            </div>
        {% endif %}
    </div><!-- .row -->
    {% endif %}

</div><!-- .row -->

project/openaid/templates/commons/top_projects.html
{% load i18n crs icons search_utils %}

{% if top_projects|length > 0 %}
    <div class="progetti">
        <h2>{% trans "Most funded projects" %}</h2>
        <div class="bordered-radius top_elements" style="overflow:hidden;">
            <div class="table-responsive table-special">
                <table class="table">
                    <tbody>
                        <thead>
                            <th scope="col"></th>
                            <th scope="col">{% trans 'Recipient' %}</th>
                            <th scope="col">€&nbsp;{% trans 'Committed' %}</th>
                            <th scope="col">€&nbsp;{% trans 'Used' %}</th>
                        </thead>
                        {% for project in top_projects %}
                            <tr>
                                <th scope="row">
                                    <a href="{{ project.get_absolute_url }}">
                                        {{ project.title|default:"Project without name" }}
                                    </a>
                                </th>
                                <td>{% if project.recipient %}{{ project.recipient.name }}{% else %}<small class="text-muted">-</small>{% endif %}</td>
                                <td>{% if project.total_commitment %}{{ project.total_commitment|currency }}{% else %}<small class="text-muted">-</small>{% endif %}</td>
                                <td>{% if project.total_disbursement %}{{ project.total_disbursement|currency }}{% else %}<small class="text-muted">-</small>{% endif %}</td>
                            </tr>
                        {% endfor %}
                        <tr style="height: 39px;">
                        <th scope="row">
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                            <td >
                                <a href="{% if object %}{% search_url object.code_list_facet object.code %}{% else %}{% url 'projects:search' %}{% endif %}"
                                    class="read-more pull-right">{% trans 'see all' %} {% icon 'align-justify' %}</a>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endif %}