project/faq/urls.py
from django.conf.urls import patterns, url
from .views import SubmitFAQ, SubmitFAQThanks,QuestionDetail, QuestionList

urlpatterns = patterns('',
    url(r'^$', QuestionList.as_view(), name='faq_question_list'),
    url(r'^(?P<slug>[\w-]+)$', QuestionDetail.as_view(), name='faq_question_detail'),

    # TODO: anonymous users can submit questions, that need approval from the editors
    # url(r'^submit$', SubmitFAQ.as_view(), 'faq_submit'),
    # url(r'^submit/thanks$', SubmitFAQThanks.as_view(), 'faq_submit_thanks'),
)

project/openaid/codelists/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from . import views

# load admin modules
from django.contrib import admin
admin.autodiscover()


urls = (
    url(r'^sectors/(?P<code>\w+)/$', views.SectorView.as_view(), name='sector-detail'),
    url(r'^recipients/(?P<code>\w+)/$', views.RecipientView.as_view(), name='recipient-detail'),
    url(r'^channels/(?P<code>\w+)/$', views.ChannelView.as_view(), name='channel-detail'),
    url(r'^agencies/(?P<code>\w+)/$', views.AgencyView.as_view(), name='agency-detail'),
    url(r'^aid_types/(?P<code>\w+)/$', views.AidTypeView.as_view(), name='aid_type-detail'),
)
urlpatterns = patterns('', *urls)

project/openaid/pages/urls.py
# -*- coding: utf-8 -*-
from .views import CooperazioneView, StaticPageView
from django.conf.urls import patterns, url, include
from .pages import  footer_sections, cooperazione_pages


urls = []

for section_id, footer_section_pages in footer_sections.items():
    for page_url_name, page_label in footer_section_pages.items():
        urls.append(
            url(r"^{0}$".format(page_url_name.replace('_', '-')),
                StaticPageView.as_view(
                    template_name="footer_{0}_{1}.html".format(section_id, page_url_name),
                    page_url_name=page_url_name,
                    page_label=page_label
                ),
                name=page_url_name
            )
        )


for page_url_name, page_label in cooperazione_pages.items():
    urls.append(
        url(r"^{0}$".format(page_url_name.replace('_', '-')),
            CooperazioneView.as_view(
                template_name="coop_{0}.html".format(page_url_name),
                page_url_name=page_url_name,
                page_label=page_label
            ),
            name=page_url_name
        )
    )

urlpatterns = patterns('', *urls)

project/openaid/projects/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from haystack.views import search_view_factory
from . import views


urls = (
    url(r'^initiative/(?P<code>\d+)/$', views.InitiativeDetail.as_view(), name='initiative-detail'),
    url(r'^project/list/$', views.ProjectList.as_view(), name='project-list'),
    url(r'^project/(?P<pk>\d+)/$', views.ProjectDetail.as_view(), name='project-detail'),
    # NOTE: search/ is here for back-compatibility
    url(r'^search/', search_view_factory(views.SearchFacetedProjectView), name='search'),
    url(r'project/search/', search_view_factory(views.SearchFacetedProjectView), name='project-search'),
    url(r'initiative/search/', search_view_factory(views.SearchFacetedInitiativeView), name='initiative-search'),

)
urlpatterns = patterns('', *urls)

project/openaid/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.routers import DefaultRouter
from . import views
from rest_framework.views import APIView
from .projects.views import ProjectViewSet, ActivityViewSet, ChannelReportedViewSet
from .codelists.views import SectorViewSet, RecipientViewSet, ChannelViewSet, AidTypeViewSet, AgencyViewSet, \
    FinanceTypeViewSet, DonorViewSet
from sitemap import sitemaps

# load admin modules
from django.contrib import admin
admin.autodiscover()


# Create a router and register our viewsets with it.
class APIRouter(DefaultRouter):

    def get_api_root_view(self):
        """
        Return a view to use as the API root.
        """
        api_root_dict = {}
        list_name = self.routes[0].name
        for prefix, viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)

        class APIRoot(APIView):
            """
            This is the root entry-point of the OpenAID APIs.

            The APIs are read-only, freely accessible to all through HTTP requests at ``http://openaid.esteri.it/api``.

            Responses are emitted in both **browseable-HTML** and **JSON** formats (``http://openaid.esteri.it/api/.json``)

            To serve all requests and avoid slow responses or downtimes due to misuse, we limit the requests rate.
            When accessing the API **anonymously**, your client is limited to **12 requests per minute** from the same IP.
            You can contact us to become an **authenticated API user** (it's still free),
            then the rate-limit would be lifted to **1 request per second**.

            If for some reasons, you need to scrape all the OpenAID data, please consider a bulk **CSV download**.

            See the ``http://openaid.esteri.it/scarica-dati/`` page in the web site.
            """
            _ignore_model_permissions = True

            def get(self, request, format=None):
                ret = {}
                for key, url_name in api_root_dict.items():
                    ret[key] = reverse(url_name, request=request, format=format)
                return Response(ret)

        return APIRoot.as_view()

router = APIRouter(trailing_slash=False)
router.register(r'projects', ProjectViewSet)
router.register(r'activities', ActivityViewSet)
router.register(r'sectors', SectorViewSet)
router.register(r'recipients', RecipientViewSet)
router.register(r'channels', ChannelViewSet)
router.register(r'aid_types', AidTypeViewSet)
router.register(r'agencies', AgencyViewSet)
router.register(r'finance_types', FinanceTypeViewSet)


urlpatterns = [
    url(r'^$', views.Home.as_view()),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^select2/', include('django_select2.urls')),
]

openaid_urls = (
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^widget/$', views.Widget.as_view(), name='widget'),
    url(r'^widget/embed/$', views.WidgetEmbed.as_view()),
    url(r'^news/', include('blog.urls')),
    url(r'^faq/', include('faq.urls')),
    url(r'^projects/', include('openaid.projects.urls', namespace='projects')),
    url(r'^code-lists/', include('openaid.codelists.urls', namespace='codelists')),
    url(r'^', include('openaid.pages.urls')),
)
urlpatterns += i18n_patterns('', *openaid_urls)

# static and media urls not works with DEBUG = True, see static function.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('', url(r'^__debug__/', include(debug_toolbar.urls)), )

# Work in progress url
if settings.MAINTENANCE:
    urlpatterns[0] = url(r'^.*$', TemplateView.as_view(template_name='work_in_progress.html'))


# Sitemap: disabled in staging
if settings.INSTANCE_TYPE != 'staging':

    urlpatterns += patterns('django.contrib.sitemaps.views',
        (r'^sitemap\.xml$', 'index', {'sitemaps': sitemaps}),
        (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap', {'sitemaps': sitemaps}),
        (r'^robots\.txt$', include('robots.urls')),
    )

project/openaid/codelists/views.py
from django.views.generic import DetailView
from django.conf import settings
from . import models
from .. import views
from .. import contexts
from openaid.codelists import serializers
from openaid.views import OpenaidViewSet
from openaid import utils

class CodeListView(views.MapFiltersContextMixin, DetailView):
    slug_field = 'code'
    slug_url_kwarg = 'code'

    def get_codelist_filter(self):
        if not hasattr(self, '_codelist_filter'):
            setattr(self, '_codelist_filter', {
                '%s__in' % self.model.code_list: self.object.get_descendants_pks(include_self=True)
            })
        return getattr(self, '_codelist_filter')

    def get_context_data(self, **kwargs):
        context = super(CodeListView, self).get_context_data(**kwargs)
        context = DetailView.get_context_data(self, **context)

        # adds model name to the context so the app knows which page of codelist it's rendering
        model_name = self.model.__name__.lower()
        context.update({'model_name': model_name})

        year_value = utils.sanitize_get_param(int,self.request.GET.get('year'),contexts.END_YEAR,top=contexts.END_YEAR,length=4)
        # depending on which codelist page it's rendereing adds top projs or top inits
        if model_name in ['agency', 'aidtype']:
            context['top_projects'] = self.object.top_projects(year=year_value)
        elif model_name in ['recipient', 'sector']:
            top_initiatives = self.object.top_initiatives()
            context['top_initiatives'] = top_initiatives[:settings.TOP_ELEMENTS_NUMBER]
            context['top_initiatives_count'] = len(top_initiatives)

        return context

    def get_map_filters(self):
        filters = super(CodeListView, self).get_map_filters()
        filters.update(self.get_codelist_filter())
        return filters


class SectorView(CodeListView):
    model = models.Sector


class RecipientView(CodeListView):
    model = models.Recipient


class ChannelView(CodeListView):
    model = models.Channel


class AidTypeView(CodeListView):
    model = models.AidType


class AgencyView(CodeListView):
    model = models.Agency


class CodelistOpenaidViewSet(OpenaidViewSet):
    lookup_field = 'code'


class SectorViewSet(CodelistOpenaidViewSet):
    queryset = models.Sector.objects.all()
    serializer_class = serializers.SectorSerializer


class RecipientViewSet(CodelistOpenaidViewSet):
    queryset = models.Recipient.objects.all()
    serializer_class = serializers.RecipientSerializer


class ChannelViewSet(CodelistOpenaidViewSet):
    queryset = models.Channel.objects.all()
    serializer_class = serializers.ChannelSerializer


class AidTypeViewSet(CodelistOpenaidViewSet):
    queryset = models.AidType.objects.all()
    serializer_class = serializers.AidTypeSerializer


class AgencyViewSet(CodelistOpenaidViewSet):
    queryset = models.Agency.objects.all()
    serializer_class = serializers.AgencySerializer


class FinanceTypeViewSet(CodelistOpenaidViewSet):
    queryset = models.FinanceType.objects.all()
    serializer_class = serializers.FinanceTypeSerializer


class DonorViewSet(CodelistOpenaidViewSet):
    queryset = models.Donor.objects.all()
    serializer_class = serializers.DonorSerializer

project/openaid/pages/views.py
# -*- coding: utf-8 -*-
import urls

from django.core.exceptions import ImproperlyConfigured
from django.views.generic import TemplateView
from django.conf import settings

class StaticPageView(TemplateView):
    """
    This view extends (monkey-patches, more precisely),
    the TemplateResponseMixin's get_template_names,
    in order to intercept the currently selected language code
    and modify the template_name.

    It is assumed that the templates will go under dedicated directory,
    named after the language codes, i.e.:

        - en
          - footer_chi_siamo.html
          - contatti.html
        - it
          - footer_chi_siamo.html
          - contatti.html

    """
    template_language = None
    page_url_name = None
    page_label = {}

    def get_template_names(self):
        """
        Returns a list of template names to be used for the request. Must return
        a list. May not be called if render_to_response is overridden.
        """
        if self.template_language is None:
            if self.request.LANGUAGE_CODE is None:
                raise ImproperlyConfigured(
                    "I18NTemplateView requires either a definition of "
                    "'template_language' or an implementation of 'get_template_language()'")
            else:
                self.template_language = self.request.LANGUAGE_CODE


        configured_languages = dict(settings.LANGUAGES).keys()
        if self.template_language is None:
            raise ImproperlyConfigured(
                "I18NTemplateView requires 'template_language' "
                "to be in one of the languages specified in the settings")

        if self.template_name is None:
            raise ImproperlyConfigured(
                "I18NTemplateView requires either a definition of "
                "'template_name' or an implementation of 'get_template_names()'")

        return ["{0}/{1}".format(self.template_language, self.template_name)]

    def get_context_data(self, **kwargs):
        context = super(StaticPageView, self).get_context_data(**kwargs)
        context['page_label'] = self.page_label
        context['page_url_name'] = self.page_url_name
        return context


class CooperazioneView(StaticPageView):
    """
    This view extends the I18NTemplateView, and is used to show
    the pages under cooperaizone_italiana.

    Basically, it injects a cooperazione_pages key, within the context.

    The cooperazione_pages is imported from the urls module (in this pages package)
    """

    def get_context_data(self, **kwargs):
        context = super(CooperazioneView, self).get_context_data(**kwargs)
        context['cooperazione_pages'] = urls.cooperazione_pages
        return context

project/openaid/views.py
from __future__ import print_function
from django.views.generic import TemplateView
from django.views.generic.base import ContextMixin
from rest_framework import viewsets
from blog.models import Entry
from django.conf import settings
from openaid import contexts
from openaid.codelists.models import Recipient
from openaid.projects.models import Project, Initiative
from openaid import utils


class MapFiltersContextMixin(ContextMixin):
    def get_context_data(self, **kwargs):
        return super(MapFiltersContextMixin, self).get_context_data(
            map_values=Recipient.get_map_totals(**self.get_map_filters()),
            **kwargs)

    def get_map_filters(self):
        # the exact lookup is necessary becouse year is already a lookup
        year_value = utils.sanitize_get_param(int,self.request.GET.get('year'),contexts.END_YEAR,top=contexts.END_YEAR,length=4)
        return {'year__exact': year_value}


class Home(MapFiltersContextMixin, TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        top_initiatives = Initiative.get_top_initiatives(is_home=True, )

        return super(Home, self).get_context_data(
            entries_list=Entry.objects.all().order_by('-published_at')[:1],
            top_initiatives=top_initiatives[:settings.TOP_ELEMENTS_NUMBER],
            top_initiatives_count=len(top_initiatives),
            **kwargs
        )

class Numbers(Home):
    template_name = 'pages/numbers.html'


class Widget(Home):
    template_name = 'widget.html'

    def get_context_data(self, **kwargs):
        return super(Widget, self).get_context_data(widget=True, **kwargs)


class WidgetEmbed(TemplateView):
    template_name = 'widget_embed.html'

    def get_context_data(self, **kwargs):
        from django.core.urlresolvers import reverse
        from django.contrib.staticfiles.templatetags.staticfiles import static
        url = self.request.build_absolute_uri(reverse('widget'))
        js_url = self.request.build_absolute_uri(static('js/widget.js'))

        return super(WidgetEmbed, self).get_context_data(widget_url=url,js_url=js_url, **kwargs)

class OpenaidViewSet(viewsets.ReadOnlyModelViewSet):
    """
    This viewset automatically provides `list` and `detail` actions.
    """
    paginate_by = 10
    paginate_by_param = 'page_size'
    max_paginate_by = 100


from rest_framework import generics


class OpenaidApiRoot(generics.GenericAPIView):
    """
    This is the root entry-point of the OpenCoesione APIs.

    The APIs are read-only, freely accessible to all through HTTP requests at ``http://www.opencoesione.gov/api``.

    Responses are emitted in both **browseable-HTML** and **JSON** formats (``http://www.opencoesione.gov/api/.json``)

    To serve all requests and avoid slow responses or downtimes due to misuse, we limit the requests rate.
    When accessing the API **anonymously**, your client is limited to **12 requests per minute** from the same IP.
    You can contact us to become an **authenticated API user** (it's still free),
    then the rate-limit would be lifted to **1 request per second**.

    Authentication is done through HTTP Basic Authentication.

    You can request a username/password to authenticate,
    by writing an email to the following address: opencoesione@dps.gov.it.

    If for some reasons, you need to scrape all the OpenCoesione data, please consider a bulk **CSV download**.
    See the ``http://www.opencoesione.gov.it/opendata/`` page in the web site.
    """

project/openaid/templates/search/facet_filters.html
{% load search_utils %}
{#{% regroup terms|dictsort:"term" by term as ordered_terms %}#}
<ul class="list-unstyled">
    {% for term in terms|dictsort:"label" %}

    {% if term.is_selected %}
    <li class="active">
        <a href="{% search_url facet term.term remove=True absolute=False %}" class="text-danger"><i class="fa fa-times"></i></a>
        {{ term.label|default:term.term }}
    </li>
    {% else %}
    <li>
        <a href="{% search_url facet term.term absolute=False %}">{{ term.label|default:term.term }}
            {% if term.count > 0 %}( <strong>{{ term.count }}</strong> ){% endif %}
        </a>
    </li>
    {% endif %}

    {% endfor %}
</ul>

project/openaid/templates/search/pagination.html
{% load i18n %}
{% load bootstrap_pagination %}
<div class="row">
    <div class="col-md-12">
        <div class="pull-right">
            {% bootstrap_paginate page range=5 %}
        </div>
    </div>
</div>

project/openaid/templates/search/project_search_results.html
{% extends 'search/search_results.html' %}

project/openaid/templates/search/search_result_element.html
{% load i18n %}
{% load crs %}

<div>



{#    <ul class="nav nav-pills ">#}
{#        {% for sector in project.sectors|unique %}#}
{#        <li>#}
{#            <a href="{% url 'codelists:sector-detail' code=sector.get_root.code %}"><span class="fa fa-chevron-right"> </span>{{ sector.get_root.name }}</a>#}
{#        </li>#}
{#        {% endfor %}#}
{#    </ul>#}
    <article class="progetti-body">
        <header>
{#            <div id="project-pie-{{ project.pk }}" data-chart="pie" data-values="{{ project.total_commitment|stringformat:"f"|default:'0' }}|{{ project.total_disbursement|stringformat:"f"|default:'0' }}"></div>#}
            {% with project_title=project.title %}
            <a href="{{ project.get_absolute_url }}">{% if project_title %}{{ project.title }}{% else %}<i>{% trans 'No title' %}</i>{% endif %}</a>
            {% endwith %}
        </header>
        <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-6">
                <span class="eleven text-upper light-gray block">{% trans 'Where does the aid go' %}</span>
                <hr>
                {% for recipient in project.recipients|unique %}
                <a href="{% url 'codelists:recipient-detail' code=recipient.code %}" class="eleven text-upper">{{ recipient.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </div>
            <div class="col-md-3 col-sm-6 col-xs-6">
                <span class="eleven text-upper light-gray block">{% trans 'What is it spent for' %}</span>
                <hr>
                {% for sector in project.sectors|unique %}
                <a href="{% url 'codelists:sector-detail' code=sector.get_root.code %}" class="eleven text-upper">{{ sector.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </div>

            {% comment %}NOTA: Questo è l'unico modo per capire se è un progetto o una inizitiva buono{% endcomment %}
            {% if project.code %}
                <div class="col-md-3 col-sm-6 col-xs-6 text-center">
                    <span class="eleven text-upper light-gray block">€ {% trans 'Total costs' %}</span>
                    <hr>
                    <div class="numbers total-cost">{% if project.total_project_costs %}{{ project.total_project_costs|currency_initiatives }}{% else %}-{% endif %}</div>
                </div>
            {% else %}
                {% with p_total_commitment=project.total_commitment|default:0 p_total_disbursement=project.total_disbursement|default:0 %}
                <div class="col-md-3 col-sm-6 col-xs-6 text-center">
                    <span class="eleven text-upper light-gray block">€ {% trans 'Committed' %}</span>
                    <br>
                    <div class="numbers bg-red bordered-radius small-pad">{% if p_total_commitment %}{{ p_total_commitment|currency }}{% else %}-{% endif %}</div>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-6 text-center">
                    <span class="eleven text-upper light-gray block">€ {% trans 'Used' %}</span>
                    <br>
                    <div class="numbers bg-blue bordered-radius small-pad">{% if p_total_disbursement %}{{ p_total_disbursement|currency }}{% else %}-{% endif %}</div>
                </div>
                {% endwith %}
            {% endif %}

{#            <div class="col-md-3 col-sm-6 col-xs-6">#}
{#                <span class="eleven light-gray block">{% trans 'Aid types' %}</span>#}
{#                {% for aid_type in project.aid_types|unique %}#}
{#                <a href="{% url 'codelists:aid_type-detail' code=aid_type.code %}" class="eleven">{{ aid_type.name }}</a>{% if not forloop.last %}, {% endif %}#}
{#                {% endfor %}#}
{#            </div>#}
{#            <div class="col-md-3 col-sm-6 col-xs-6">#}
{#                <span class="eleven light-gray block">{% trans 'Channels' %}</span>#}
{#                {% for channel in project.channels|unique %}#}
{#                <a href="{% url 'codelists:channel-detail' code=channel.code %}" class="eleven">{{ channel.name }}</a>{% if not forloop.last %}, {% endif %}#}
{#                {% endfor %}#}
{#            </div>#}
         </div><!-- .row -->
{#        {% if project.recipient %}#}
{#        <div class="row">#}
{#            <div class="col-md-12">#}
{#                {% for recipient in project.recipients|unique %}#}
{#                <a href="{% url 'codelists:recipient-detail' code=recipient.code %}" class="twelve">{{ recipient.name }}</a>#}
{#                {% endfor %}#}
{#            </div>#}
{#        </div>#}
{#        {% endif %}#}
    </article>
</div>

project/openaid/templates/search/search_results.html
{% extends 'base.html' %}

{% load i18n %}
{% load icons %}
{% load humanize %}
{% load search_utils %}
{% load staticfiles %}

{% block page_title %}OpenAID - {% trans "Search" %}{% endblock %}
{% block og_title %}OpenAID - {% trans "Search" %}{% endblock %}

{% block css %}
    {{ block.super }}
    <style>
    #results-header {
        margin-top: 20px;
        margin-bottom: 20px;
    }
    #results-header .nav .pagination {
        margin: 0;
    }
    #results-header .nav > li.active > a {
        background-color: #fff;
        color: #555;
    }
    #results-header .nav > li > a {
        background-color: #f7505a;
        color: white;
    }
    #results-header .nav .lead {
        margin-bottom: 0;
        margin-right: 20px;
        float: left;
    }
    .text-upper { text-transform: uppercase !important; }
    #main-content .filters .edit-filters {
        border-bottom: 1px solid #ddd;
    }
    #main-content .progetti article.progetti-body header {
        border: 0;
        min-height: 10px;
    }
    #main-content .progetti article.progetti-body .light-gray {
        color: #8D8D8D;
        font-weight: bold;
    }
    #main-content .progetti article.progetti-body hr {
        margin: 5px 0;
    }
    section.filters .list-unstyled a {
        color: #8D8D8D;
    }
    #main-content .progetti article.progetti-body .total-cost {
        color: #f7505a;
        font-weight: bold;
    }
    #main-content .progetti ul li .row {
         line-height: .8em;
    }
    #main-content .progetti ul li {
        border-bottom: 1px solid #ddd;
    }
    </style>
{% endblock %}

{% block body_header %}
    {{ block.super }}
    {% if search_facets %}
    <div class="container">
        <div id="main-title">
            <h1>{% trans 'Projects' %}: {% for facet, term in search_facets %}{{ term }}{% if not forloop.last %}, {% endif %}{% endfor %}</h1>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block content %}
<div class="container" id="results-header">
    <div class="row">
        <div class="col-md-12">
            <ul class="nav nav-tabs">
                <li{% if 'initiatives' in search_using %} class="active"{% endif %}><a href="{% url 'projects:initiative-search' %}">{% trans "Initiatives" %}</a></li>
                <li{% if 'default' in search_using %} class="active"{% endif %}><a href="{% url 'projects:project-search' %}">{% trans "Projects" %}</a></li>
                <li class="pull-right">

                    {% include 'search/pagination.html' %}</li>
                <li class="pull-right">
                    <p class="lead"><strong>{{ n_results }}</strong> {% trans "Search results" %}</p>
                </li>
            </ul>

        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="progetti">
                <div class="" style="overflow:hidden;">
                    <ul class="list-unstyled">
                        {% for result in page.object_list %}
                        <li>
                            {% include 'search/search_result_element.html' with project=result.object %}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="ordering">
                {% include 'search/pagination.html' %}
            </div>
        </div>
        <div class="col-md-4">
{#            <section class="filters">#}
{#                <div class="filter-labels">{% trans 'Search' %}</div>#}
{#                <div class="filter-content">#}
{#                    <form class="form-inline" role="form">#}
{#                        <div class="form-group has-feedback eleven">#}
{#                            <label class="sr-only" for="exampleInputEmail2">Email address</label>#}
{#                            <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Una parola chiave nel nome">#}
{#                            <span class="fa fa-times form-control-feedback"></span>#}
{#                        </div>#}
{#                        <div class="form-group has-feedback eleven">#}
{#                            <label class="sr-only" for="exampleInputPassword2">Password</label>#}
{#                            <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Un'area geografica">#}
{#                            <span class="fa fa-times form-control-feedback"></span>#}
{#                        </div>#}
{#                        <button type="submit" class="btn btn-aid btn-inline">cerca <span class="fa fa-search"></span></button>#}
{#                        <div class="checkbox">#}
{#                            <label class="eleven">#}
{#                                <input type="checkbox"> CERCA TRA I RISULTATI#}
{#                            </label>#}
{#                        </div>#}
{#                    </form>#}
{#                </div>#}
{#            </section>#}

            <section class="filters">

                <div class="filter-content">
                    <div class="edit-filters"><h3 class="text-upper">{% trans "Filters" %}</h3></div>
                    <div class="edit-filters">

                        <h4 class="text-upper">{% trans "Edit filters" %} <small class="pull-right eleven">{% trans "Remove filters" %}
                            <a href="{% if 'default' in search_using %}{% url 'projects:project-search' %}{% else %}{% url 'projects:initiative-search' %}{% endif %}">{% icon 'times' %}</a>
                        </small></h4>
                    </div>
{#                    <div class="edit-filters">#}
{#                        <p class="eleven no-marg-all filter-typology">TIPOLOGIA</p>#}
{#                        <span class="eleven">Tipologia Lorem ipsum <a class="fa fa-times"> </a></span>#}
{#                    </div>#}
{#                    <h4>Fondi impegnati</h4>#}
{#                    <img src="{% static 'img/layout/finanziamenti.jpg' %}">#}
{#                    <div class="small-spacer"> </div>#}
{% block facets-sidebar %}
                    <div class="edit-filters">
                        <h4>{% trans 'Sector' %}</h4>
                        {% show_facets 'sectors' codelist='sector' %}
                    </div>
                    <div class="edit-filters">
                        <h4>{% trans 'Agency' %}</h4>
                        {% show_facets 'agencies' codelist='agency' %}
                    </div>
                    <div class="edit-filters">
                        <h4>{% trans 'Year' %}</h4>
                        {% show_facets 'years' %}
                    </div>
                    <div class="edit-filters">
                        <h4>{% trans 'Aid type' %}</h4>
                        {% show_facets 'aid_types' codelist='aid_type' %}
                    </div>
                    <div class="edit-filters">
                        <h4>{% trans 'Finance type' %}</h4>
                        {% show_facets 'finance_types' codelist='finance_type' %}
                    </div>
                    <div class="edit-filters">
                        <h4>{% trans 'Channel' %}</h4>
                        {% show_facets 'channels' codelist='channel' %}
                    </div>
                    <div class="edit-filters">
                        <h4>{% trans 'Recipient' %}</h4>
                        <div class="readmore" data-max-height="200">
                            {% show_facets 'recipient' codelist='recipient' %}
                            <a href="#" class="readmore-open">{% trans 'read more' %} {% icon 'caret-down' %}</a>
                            <a href="#" class="readmore-close">{% trans 'close' %} {% icon 'caret-up' %}</a>
                        </div>
                    </div>
{% endblock facets-sidebar %}


                </div>
            </section>
        </div>
    </div><!-- /.row -->
</div><!-- /.container -->


{% endblock %}