project/faq/urls.py
from django.conf.urls import patterns, url
from .views import SubmitFAQ, SubmitFAQThanks,QuestionDetail, QuestionList

urlpatterns = patterns('',
    url(r'^$', QuestionList.as_view(), name='faq_question_list'),
    url(r'^(?P<slug>[\w-]+)$', QuestionDetail.as_view(), name='faq_question_detail'),

    # TODO: anonymous users can submit questions, that need approval from the editors
    # url(r'^submit$', SubmitFAQ.as_view(), 'faq_submit'),
    # url(r'^submit/thanks$', SubmitFAQThanks.as_view(), 'faq_submit_thanks'),
)

project/openaid/codelists/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from . import views

# load admin modules
from django.contrib import admin
admin.autodiscover()


urls = (
    url(r'^sectors/(?P<code>\w+)/$', views.SectorView.as_view(), name='sector-detail'),
    url(r'^recipients/(?P<code>\w+)/$', views.RecipientView.as_view(), name='recipient-detail'),
    url(r'^channels/(?P<code>\w+)/$', views.ChannelView.as_view(), name='channel-detail'),
    url(r'^agencies/(?P<code>\w+)/$', views.AgencyView.as_view(), name='agency-detail'),
    url(r'^aid_types/(?P<code>\w+)/$', views.AidTypeView.as_view(), name='aid_type-detail'),
)
urlpatterns = patterns('', *urls)

project/openaid/pages/urls.py
# -*- coding: utf-8 -*-
from .views import CooperazioneView, StaticPageView
from django.conf.urls import patterns, url, include
from .pages import  footer_sections, cooperazione_pages


urls = []

for section_id, footer_section_pages in footer_sections.items():
    for page_url_name, page_label in footer_section_pages.items():
        urls.append(
            url(r"^{0}$".format(page_url_name.replace('_', '-')),
                StaticPageView.as_view(
                    template_name="footer_{0}_{1}.html".format(section_id, page_url_name),
                    page_url_name=page_url_name,
                    page_label=page_label
                ),
                name=page_url_name
            )
        )


for page_url_name, page_label in cooperazione_pages.items():
    urls.append(
        url(r"^{0}$".format(page_url_name.replace('_', '-')),
            CooperazioneView.as_view(
                template_name="coop_{0}.html".format(page_url_name),
                page_url_name=page_url_name,
                page_label=page_label
            ),
            name=page_url_name
        )
    )

urlpatterns = patterns('', *urls)

project/openaid/projects/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from haystack.views import search_view_factory
from . import views


urls = (
    url(r'^initiative/(?P<code>\d+)/$', views.InitiativeDetail.as_view(), name='initiative-detail'),
    url(r'^project/list/$', views.ProjectList.as_view(), name='project-list'),
    url(r'^project/(?P<pk>\d+)/$', views.ProjectDetail.as_view(), name='project-detail'),
    # NOTE: search/ is here for back-compatibility
    url(r'^search/', search_view_factory(views.SearchFacetedProjectView), name='search'),
    url(r'project/search/', search_view_factory(views.SearchFacetedProjectView), name='project-search'),
    url(r'initiative/search/', search_view_factory(views.SearchFacetedInitiativeView), name='initiative-search'),

)
urlpatterns = patterns('', *urls)

project/openaid/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.routers import DefaultRouter
from . import views
from rest_framework.views import APIView
from .projects.views import ProjectViewSet, ActivityViewSet, ChannelReportedViewSet
from .codelists.views import SectorViewSet, RecipientViewSet, ChannelViewSet, AidTypeViewSet, AgencyViewSet, \
    FinanceTypeViewSet, DonorViewSet
from sitemap import sitemaps

# load admin modules
from django.contrib import admin
admin.autodiscover()


# Create a router and register our viewsets with it.
class APIRouter(DefaultRouter):

    def get_api_root_view(self):
        """
        Return a view to use as the API root.
        """
        api_root_dict = {}
        list_name = self.routes[0].name
        for prefix, viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)

        class APIRoot(APIView):
            """
            This is the root entry-point of the OpenAID APIs.

            The APIs are read-only, freely accessible to all through HTTP requests at ``http://openaid.esteri.it/api``.

            Responses are emitted in both **browseable-HTML** and **JSON** formats (``http://openaid.esteri.it/api/.json``)

            To serve all requests and avoid slow responses or downtimes due to misuse, we limit the requests rate.
            When accessing the API **anonymously**, your client is limited to **12 requests per minute** from the same IP.
            You can contact us to become an **authenticated API user** (it's still free),
            then the rate-limit would be lifted to **1 request per second**.

            If for some reasons, you need to scrape all the OpenAID data, please consider a bulk **CSV download**.

            See the ``http://openaid.esteri.it/scarica-dati/`` page in the web site.
            """
            _ignore_model_permissions = True

            def get(self, request, format=None):
                ret = {}
                for key, url_name in api_root_dict.items():
                    ret[key] = reverse(url_name, request=request, format=format)
                return Response(ret)

        return APIRoot.as_view()

router = APIRouter(trailing_slash=False)
router.register(r'projects', ProjectViewSet)
router.register(r'activities', ActivityViewSet)
router.register(r'sectors', SectorViewSet)
router.register(r'recipients', RecipientViewSet)
router.register(r'channels', ChannelViewSet)
router.register(r'aid_types', AidTypeViewSet)
router.register(r'agencies', AgencyViewSet)
router.register(r'finance_types', FinanceTypeViewSet)


urlpatterns = [
    url(r'^$', views.Home.as_view()),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^select2/', include('django_select2.urls')),
]

openaid_urls = (
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^widget/$', views.Widget.as_view(), name='widget'),
    url(r'^widget/embed/$', views.WidgetEmbed.as_view()),
    url(r'^news/', include('blog.urls')),
    url(r'^faq/', include('faq.urls')),
    url(r'^projects/', include('openaid.projects.urls', namespace='projects')),
    url(r'^code-lists/', include('openaid.codelists.urls', namespace='codelists')),
    url(r'^', include('openaid.pages.urls')),
)
urlpatterns += i18n_patterns('', *openaid_urls)

# static and media urls not works with DEBUG = True, see static function.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('', url(r'^__debug__/', include(debug_toolbar.urls)), )

# Work in progress url
if settings.MAINTENANCE:
    urlpatterns[0] = url(r'^.*$', TemplateView.as_view(template_name='work_in_progress.html'))


# Sitemap: disabled in staging
if settings.INSTANCE_TYPE != 'staging':

    urlpatterns += patterns('django.contrib.sitemaps.views',
        (r'^sitemap\.xml$', 'index', {'sitemaps': sitemaps}),
        (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap', {'sitemaps': sitemaps}),
        (r'^robots\.txt$', include('robots.urls')),
    )

project/openaid/codelists/views.py
from django.views.generic import DetailView
from django.conf import settings
from . import models
from .. import views
from .. import contexts
from openaid.codelists import serializers
from openaid.views import OpenaidViewSet
from openaid import utils

class CodeListView(views.MapFiltersContextMixin, DetailView):
    slug_field = 'code'
    slug_url_kwarg = 'code'

    def get_codelist_filter(self):
        if not hasattr(self, '_codelist_filter'):
            setattr(self, '_codelist_filter', {
                '%s__in' % self.model.code_list: self.object.get_descendants_pks(include_self=True)
            })
        return getattr(self, '_codelist_filter')

    def get_context_data(self, **kwargs):
        context = super(CodeListView, self).get_context_data(**kwargs)
        context = DetailView.get_context_data(self, **context)

        # adds model name to the context so the app knows which page of codelist it's rendering
        model_name = self.model.__name__.lower()
        context.update({'model_name': model_name})

        year_value = utils.sanitize_get_param(int,self.request.GET.get('year'),contexts.END_YEAR,top=contexts.END_YEAR,length=4)
        # depending on which codelist page it's rendereing adds top projs or top inits
        if model_name in ['agency', 'aidtype']:
            context['top_projects'] = self.object.top_projects(year=year_value)
        elif model_name in ['recipient', 'sector']:
            top_initiatives = self.object.top_initiatives()
            context['top_initiatives'] = top_initiatives[:settings.TOP_ELEMENTS_NUMBER]
            context['top_initiatives_count'] = len(top_initiatives)

        return context

    def get_map_filters(self):
        filters = super(CodeListView, self).get_map_filters()
        filters.update(self.get_codelist_filter())
        return filters


class SectorView(CodeListView):
    model = models.Sector


class RecipientView(CodeListView):
    model = models.Recipient


class ChannelView(CodeListView):
    model = models.Channel


class AidTypeView(CodeListView):
    model = models.AidType


class AgencyView(CodeListView):
    model = models.Agency


class CodelistOpenaidViewSet(OpenaidViewSet):
    lookup_field = 'code'


class SectorViewSet(CodelistOpenaidViewSet):
    queryset = models.Sector.objects.all()
    serializer_class = serializers.SectorSerializer


class RecipientViewSet(CodelistOpenaidViewSet):
    queryset = models.Recipient.objects.all()
    serializer_class = serializers.RecipientSerializer


class ChannelViewSet(CodelistOpenaidViewSet):
    queryset = models.Channel.objects.all()
    serializer_class = serializers.ChannelSerializer


class AidTypeViewSet(CodelistOpenaidViewSet):
    queryset = models.AidType.objects.all()
    serializer_class = serializers.AidTypeSerializer


class AgencyViewSet(CodelistOpenaidViewSet):
    queryset = models.Agency.objects.all()
    serializer_class = serializers.AgencySerializer


class FinanceTypeViewSet(CodelistOpenaidViewSet):
    queryset = models.FinanceType.objects.all()
    serializer_class = serializers.FinanceTypeSerializer


class DonorViewSet(CodelistOpenaidViewSet):
    queryset = models.Donor.objects.all()
    serializer_class = serializers.DonorSerializer

project/openaid/pages/views.py
# -*- coding: utf-8 -*-
import urls

from django.core.exceptions import ImproperlyConfigured
from django.views.generic import TemplateView
from django.conf import settings

class StaticPageView(TemplateView):
    """
    This view extends (monkey-patches, more precisely),
    the TemplateResponseMixin's get_template_names,
    in order to intercept the currently selected language code
    and modify the template_name.

    It is assumed that the templates will go under dedicated directory,
    named after the language codes, i.e.:

        - en
          - footer_chi_siamo.html
          - contatti.html
        - it
          - footer_chi_siamo.html
          - contatti.html

    """
    template_language = None
    page_url_name = None
    page_label = {}

    def get_template_names(self):
        """
        Returns a list of template names to be used for the request. Must return
        a list. May not be called if render_to_response is overridden.
        """
        if self.template_language is None:
            if self.request.LANGUAGE_CODE is None:
                raise ImproperlyConfigured(
                    "I18NTemplateView requires either a definition of "
                    "'template_language' or an implementation of 'get_template_language()'")
            else:
                self.template_language = self.request.LANGUAGE_CODE


        configured_languages = dict(settings.LANGUAGES).keys()
        if self.template_language is None:
            raise ImproperlyConfigured(
                "I18NTemplateView requires 'template_language' "
                "to be in one of the languages specified in the settings")

        if self.template_name is None:
            raise ImproperlyConfigured(
                "I18NTemplateView requires either a definition of "
                "'template_name' or an implementation of 'get_template_names()'")

        return ["{0}/{1}".format(self.template_language, self.template_name)]

    def get_context_data(self, **kwargs):
        context = super(StaticPageView, self).get_context_data(**kwargs)
        context['page_label'] = self.page_label
        context['page_url_name'] = self.page_url_name
        return context


class CooperazioneView(StaticPageView):
    """
    This view extends the I18NTemplateView, and is used to show
    the pages under cooperaizone_italiana.

    Basically, it injects a cooperazione_pages key, within the context.

    The cooperazione_pages is imported from the urls module (in this pages package)
    """

    def get_context_data(self, **kwargs):
        context = super(CooperazioneView, self).get_context_data(**kwargs)
        context['cooperazione_pages'] = urls.cooperazione_pages
        return context

project/openaid/views.py
from __future__ import print_function
from django.views.generic import TemplateView
from django.views.generic.base import ContextMixin
from rest_framework import viewsets
from blog.models import Entry
from django.conf import settings
from openaid import contexts
from openaid.codelists.models import Recipient
from openaid.projects.models import Project, Initiative
from openaid import utils


class MapFiltersContextMixin(ContextMixin):
    def get_context_data(self, **kwargs):
        return super(MapFiltersContextMixin, self).get_context_data(
            map_values=Recipient.get_map_totals(**self.get_map_filters()),
            **kwargs)

    def get_map_filters(self):
        # the exact lookup is necessary becouse year is already a lookup
        year_value = utils.sanitize_get_param(int,self.request.GET.get('year'),contexts.END_YEAR,top=contexts.END_YEAR,length=4)
        return {'year__exact': year_value}


class Home(MapFiltersContextMixin, TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        top_initiatives = Initiative.get_top_initiatives(is_home=True, )

        return super(Home, self).get_context_data(
            entries_list=Entry.objects.all().order_by('-published_at')[:1],
            top_initiatives=top_initiatives[:settings.TOP_ELEMENTS_NUMBER],
            top_initiatives_count=len(top_initiatives),
            **kwargs
        )

class Numbers(Home):
    template_name = 'pages/numbers.html'


class Widget(Home):
    template_name = 'widget.html'

    def get_context_data(self, **kwargs):
        return super(Widget, self).get_context_data(widget=True, **kwargs)


class WidgetEmbed(TemplateView):
    template_name = 'widget_embed.html'

    def get_context_data(self, **kwargs):
        from django.core.urlresolvers import reverse
        from django.contrib.staticfiles.templatetags.staticfiles import static
        url = self.request.build_absolute_uri(reverse('widget'))
        js_url = self.request.build_absolute_uri(static('js/widget.js'))

        return super(WidgetEmbed, self).get_context_data(widget_url=url,js_url=js_url, **kwargs)

class OpenaidViewSet(viewsets.ReadOnlyModelViewSet):
    """
    This viewset automatically provides `list` and `detail` actions.
    """
    paginate_by = 10
    paginate_by_param = 'page_size'
    max_paginate_by = 100


from rest_framework import generics


class OpenaidApiRoot(generics.GenericAPIView):
    """
    This is the root entry-point of the OpenCoesione APIs.

    The APIs are read-only, freely accessible to all through HTTP requests at ``http://www.opencoesione.gov/api``.

    Responses are emitted in both **browseable-HTML** and **JSON** formats (``http://www.opencoesione.gov/api/.json``)

    To serve all requests and avoid slow responses or downtimes due to misuse, we limit the requests rate.
    When accessing the API **anonymously**, your client is limited to **12 requests per minute** from the same IP.
    You can contact us to become an **authenticated API user** (it's still free),
    then the rate-limit would be lifted to **1 request per second**.

    Authentication is done through HTTP Basic Authentication.

    You can request a username/password to authenticate,
    by writing an email to the following address: opencoesione@dps.gov.it.

    If for some reasons, you need to scrape all the OpenCoesione data, please consider a bulk **CSV download**.
    See the ``http://www.opencoesione.gov.it/opendata/`` page in the web site.
    """

project/openaid/templates/base_map.html
{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}

{% block css %}

    {{ block.super }}

    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" />
     <!--[if lte IE 8]>
         <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.ie.css" />
     <![endif]-->

    <script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>

{% endblock %}

{% block content %}
<div id="map"></div>
{% endblock %}

{% block javascript %}

    {{ block.super }}

    <!-- countries geojson with labels, put into >states< js variable -->
    <script type="text/javascript" src="{% static 'js/countries.js' %}"></script>

    <!-- merge totals extracted from DB into >states< geoJson -->
    <script type="text/javascript">
    var statesData ={// alpha 3 iso code
    {% for t in map_values %}
        "{{ t.iso_code }}": {
            "label": "{{ t.label }}",
            "url": "{% url 'codelists:recipient-detail' code=t.code %}?year={{ selected_year }}",
            "value": "{{ t.value|default:"0" }}".replace(/,/g, '.')
        }{% if not forloop.last %},{% endif %}
    {% endfor %}
    };

    $.each(states.features, function(index, feature){
        id = feature.id;
        if (id in statesData){
            feature.properties.url = statesData[id].url;
            feature.properties.label = statesData[id].label;
            feature.properties.value = statesData[id].value;
        }
    });

    </script>

    <script type="text/javascript" src="{% static 'js/humanize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/map_'|add:LANGUAGE_CODE|add:'.js' %}"></script>

{% endblock %}

project/openaid/templates/cookies.html
<div class="wrapper-cookies" id="accept-cookies">
    <div class="container">
        <div class="accept-cookies" >
            Questo sito usa cookie per fornirti un'esperienza migliore. Proseguendo la navigazione accetti l'utilizzo dei cookie da parte nostra
            <span id="dismiss-cookie-adv" class="btn btn-danger">OK</span>
            <a href="{% url 'privacy' %}" id="dismiss-cookie-adv" class="btn btn-danger">Approfondisci</a>
        </div>
    </div>
    <div id="up"></div>
</div>

project/openaid/templates/earlybird.html
{% load staticfiles i18n icons %}{% get_current_language as LANGUAGE_CODE %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <title>{% block page_title %}OpenAID{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block page_description %}{% endblock %}">
    <meta name="author" content="{% block page_author %}depp srl{% endblock %}">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'js/vendor/bootstrap/css/bootstrap.css' %}">

    <style>
        body {
          padding-top: 40px;
            padding-bottom: 40px;
            background-color: #eee;
        }

        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin .checkbox {
            font-weight: normal;
        }
        .form-signin .form-control {
            position: relative;
            height: auto;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            padding: 10px;
            font-size: 16px;
        }
        .form-signin .form-control:focus {
            z-index: 2;
        }
        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"><!-- Major Browsers -->
    <!--[if IE]><link rel="SHORTCUT ICON" href="{% static 'img/favicon.ico' %}"/><![endif]--><!-- Internet Explorer-->
</head>

<body>



<div class="container" style="margin-top: 150px;">

    <div class="row">

        <div class="col-md-4 col-md-offset-4">
            <img src="{% static 'img/layout/logo_openaid.png' %}" class="img-responsive" id="main-logo">

{#            <form class="form-signin collapse" role="form" method="post" action="/admin/">{% csrf_token %}#}
{#                <input type="hidden" name="next" value="/"/>#}
{#                <input type="text" name="username" class="form-control" placeholder="Username" required autofocus>#}
{#                <input type="password" name="password" class="form-control" placeholder="Password" required>#}
{#                <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>#}
{#            </form>#}
        </div>



    </div>



</div> <!-- /container -->


<!-- Latest JQuery -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-980632-27', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

project/openaid/templates/navbar.html
{% load i18n %}
<div id="main-menu" class="bg-red">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <nav class="navbar navbar-default navbar-main" role="navigation">
                    <ul class="nav navbar-nav">
                        <li><a href="#" class="dropdown-toggle first" data-toggle="dropdown">{% trans 'Where does the aid go' %}? <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                {% for recipient, children in recipients %}{% if recipient.activity_count > 0 %}
                                {% if children|length > 0 %}
                                <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown">{{ recipient.name }}</a>
                                    <ul class="dropdown-menu">
                                        {% for child in children|dictsort:'name' %}{% if child.activity_count > 0 %}
                                        <li><a href="{% if work_in_progress %}{% else %}{% url 'codelists:recipient-detail' code=child.code %}{% endif %}">{{ child.name }}</a></li>
                                        {% endif %}{% endfor %}
                                    </ul>
                                </li>
                                {% else %}
                                <li>
                                    <a href="{% if work_in_progress %}{% else %}{% url 'codelists:recipient-detail' code=recipient.code %}{% endif %}">{{ recipient.name }}</a>
                                </li>
                                {% endif %}{% endif %}
                                {% endfor %}
                            </ul>
                        </li>
                        <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'What is it spent for' %}? <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                {% for sector in sectors|dictsort:'code' %}{% if sector.activity_count > 0 %}
                                <li>
                                    <a href="{% if work_in_progress %}{% else %}{% url 'codelists:sector-detail' code=sector.code %}{% endif %}">{{ sector.name }}</a>
                                </li>
                                {% endif %}{% endfor %}
                            </ul>
                        </li>
                        <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'Who funds?' %} <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                {% for agency in agencies|dictsort:'code' %}{% if agency.activity_count > 0 %}
                                <li>
                                    <a href="{% if work_in_progress %}{% else %}{% url 'codelists:agency-detail' code=agency.code %}{% endif %}">{{ agency.name }}</a>
                                </li>
                                {% endif %}{% endfor %}
                            </ul>
                        </li>
                        <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'By means of?' %} <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                {% for aid_type in aid_types|dictsort:'code' %}{% if aid_type.activity_count > 0 %}
                                <li>
                                    <a href="{% if work_in_progress %}{% else %}{% url 'codelists:aid_type-detail' code=aid_type.code %}{% endif %}">{{ aid_type.name }}</a>
                                </li>
                                {% endif %}{% endfor %}

                            </ul>
                        </li>
                    </ul>
                    {% if work_in_progress %}

                    {% else %}
                        <form class="navbar-form navbar-right" action="{% url 'projects:initiative-search' %}" method="get" role="search">

                            <div class="search-form">
                                <div class="form-white">
                                    <input class="form-control" id="search-input" name="{{ search_form.q.html_name }}"
                                       value="{{ search_form.q.value|default_if_none:'' }}"
                                       type="text" placeholder="{% trans "Search" %}">
                                    {#<ul class="{% comment %}nav navbar-nav pull-right">#}
                                    {#    <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">REALIZZATORI<b class="caret"></b></a>#}
                                    {#        <ul class="dropdown-menu">#}
                                    {#            <li><a href="#">Action</a></li>#}
                                    {#            <li><a href="#">Action</a></li>#}
                                    {#        </ul>#}
                                    {#    </li>#}
                                    {#</ul>{% endcomment %}#}
                                </div>
                                <button type="submit" class="fa fa-search" style="float:right"> </button>
                            </div>
                        </form>
                    {% endif %}
                </nav>
            </div><!-- .col-md-12 -->
        </div><!-- .row -->
    </div><!-- .container -->
</div>

project/openaid/templates/widget.html
{% extends 'base_map.html' %}
{% load i18n %}
{% load staticfiles %}
{% load idioticon %}
{% load icons %}
{% load humanize %}
{% load crs %}

{% block body_header %}{% endblock %}
{% block body_footer %}{% endblock %}
{% block cookies %}{% endblock %}


{% block body_content %}

    <div id="main-content">
    <div class="container">

        {% crs_stats %}
    </div>
    </div>



{% endblock %}

{% block javascript %}

    <script>window.is_widget = true;</script>

    {{ block.super }}

{% endblock %}